site_name: Slay The Spire - Murder Mystery

theme:
  name: material
  logo: images/SneckoEye.png
  favicon: images/SneckoEye.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
    - content.code.copy
  palette:
    - scheme: slate
      primary: yellow
      accent: deep purple
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 2
nav:
  - Welcome: index.md
  - How to Play: rules.md
  - Timeline: timeline.md
  - Rumors: rumors.md
  - Fights & Rewards: fights.md
  - Store & Potions: store.md
  - Voting & Winning: voting.md
  - Murder: murder.md
  - FAQ: faq.md
extra:
  generator: false
